[workspace]
members = [
    "vapp01",
    "vlib01",
]
default-members = [
    "vlib01",
]

[package]
name = "workspace-play"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]

[workspace.package]
homepage = "https://blog.only1u.org"